-- wkstationz Hyprland configuration (Hyprland 0.55+ Lua API)
-- See https://wiki.hypr.land/Configuring/Start/ for available keywords.

-- Monitor layout: generated by the installer into monitors.lua
if is_file_exists(HOME .. "/.config/hypr/monitors.lua") then
    require("monitors")
end

-- Programs
local terminal    = "kitty"
local fileManager = "thunar"
local browser     = "brave"

-- Environment
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("quickshell")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-paste --watch cliphist store")
end)

-- Look and feel: no gaps, no rounding, dark border colors
hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 2,
        col = {
            active_border   = "rgba(7aa2f7ee)",
            inactive_border = "rgba(414868aa)",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },
    decoration = {
        rounding = 0,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = false,
        },
        blur = {
            enabled = false,
        },
    },
    dwindle = {
        preserve_split = true,
        pseudotile = true,
    },
    misc = {
        force_default_wallpaper = -1, -- keep Hyprland's default wallpaper behavior
        disable_hyprland_logo = false,
    },
})

-- Animations: subtle, not over the top
hl.curve("smooth", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.animation({ leaf = "windows",    enabled = true, speed = 5,   bezier = "smooth" })
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 5,   bezier = "smooth", style = "popin 90%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3,   bezier = "smooth", style = "popin 90%" })
hl.animation({ leaf = "fade",       enabled = true, speed = 4,   bezier = "smooth" })
hl.animation({ leaf = "layers",     enabled = true, speed = 4,   bezier = "smooth" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4,   bezier = "smooth", style = "slide" })

-- Input
hl.config({
    input = {
        kb_layout = "pt",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Load user keybinds
if is_file_exists(HOME .. "/.config/hypr/keybinds.lua") then
    require("keybinds")
end
